#!/bin/bash

set -x

objects=(csi-cephfsplugin-provisioner csi-cephfsplugin csi-provisioner-rbac csi-nodeplugin-rbac)

for obj in "${objects[@]}"; do
	kubectl delete -f "./$obj.yaml"
done

kubectl delete configmap ceph-config
kubectl delete configmap ceph-csi-config
kubectl delete storageclass csi-cephfs-sc
kubectl delete secret csi-cephfs-secret
