#!/bin/bash

set -x

#./init-ceph-csi-from-vstart-cluster
#./init-ceph-csi-encrypted-storage-class
./init-ceph-csi-from-rook 

K8S () {
    kubectl --namespace irq0 "${@}"
}

objects=(csi-provisioner-rbac csi-nodeplugin-rbac
	 csi-cephfsplugin-provisioner csi-cephfsplugin
	 csi-rbdplugin-provisioner csi-rbdplugin
	 csi-nodeplugin-psp csi-provisioner-psp
	 deployment-encrypted-sc)

for obj in "${objects[@]}"; do
	K8S apply -f "./$obj.yaml"
done
